### ISSUE TITLE
Update new group

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-rss#8]
After this PR https://github.com/micronaut-projects/micronaut-rss/pull/7 is merged, it is necessary to:

- Document the new package like https://github.com/micronaut-projects/micronaut-core/commit/41b189bc6d9d0d406d1d268fba250eed6615a467 
- Modify the Starter with the new package
- Update the new group in the BOM: https://github.com/micronaut-projects/micronaut-core/blob/master/build.gradle#L622

**Comment by sdelamo** [comment]
https://github.com/micronaut-projects/micronaut-starter/commit/e9c46009666ee64a5da3c8ca491857e928415be0
